"""
Api class for our api routes and json data field names
"""

class Api(object):
    api = 'api'
    session = 'session'
    users = 'users'
    channels = 'channels'
    emails = 'emails'
    password = 'password'
    config = 'config'
    profile = 'profile'
    pm = 'pm'

    username_param = '<username>'
    user_param = '<user>'
    msg_id_param = '<msg_id>'
    channel_param = '<channel>'

    msg_id_p = 'msg_id'

    session_key = 'session-key'
    username = 'username'
    user = 'user'
    email = 'email'
    users = 'users'
    email_code = 'code'
    blocked = 'blocked'
    chat_filter = 'chat-filter'
    default_chat_filter = 'none'
    firstname = 'first-name'
    lastname = 'last-name'
    bio = 'bio'
    gender = 'gender'
    sender = 'sender'
    msg_id = 'msg-id'
    msg = 'msg'
    timestamp = 'timestamp'
    message = 'message'
    messages = 'messages'
    channel = 'channel'
    channels = 'channels'
    channel_name = 'channel-name'
    time_end = 'time-end'
    subscriptions = 'subscriptions'
    black_list = 'black-list'
    time = 'time'
    admins = 'admins'
    chief_admin = 'chief-admin'
    chat = 'chat'
    web = 'web'

